import type { Metadata } from 'next'
import { Fira_Sans } from 'next/font/google'
import './globals.scss'

export const metadata: Metadata = {
  title: 'Ride.Rent',
  description: 'Generated by create next app',
}

const firaSans = Fira_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={firaSans.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}
