export const VEHICLE_TYPES = [
  {
    key: 1,
    name: 'Luxury',
    options: 10,
    value: 'luxury',
    src: '/assets/img/vehicle types/car types/LUXURY.webp',
  },
  {
    key: 2,
    name: 'Car With Driver',
    options: 8,
    value: 'car_with_driver',
    src: '/assets/img/vehicle types/car types/CAR WITH DRIVER.webp',
  },
  {
    key: 3,
    name: 'Airport Pickup',
    options: 5,
    value: 'airport_pickup',
    src: '/assets/img/vehicle types/car types/AIRPORT PICKUP.webp',
  },
  {
    key: 4,
    name: 'SUVs',
    options: 7,
    value: 'suvs',
    src: '/assets/img/vehicle types/car types/SUVs.webp',
  },
  {
    key: 5,
    name: 'Desert Safari',
    options: 6,
    value: 'desert_safari',
    src: '/assets/img/vehicle types/car types/DESERT SAFARI.webp',
  },
  {
    key: 6,
    name: 'Monthly Rentals',
    options: 9,
    value: 'monthly_rentals',
    src: '/assets/img/vehicle types/car types/MONTHLY RENTALS.webp',
  },
  {
    key: 7,
    name: 'Electric Cars',
    options: 4,
    value: 'electric_cars',
    src: '/assets/img/vehicle types/car types/ELECTRIC CARS.webp',
  },
  {
    key: 8,
    name: 'Convertible',
    options: 3,
    value: 'convertible',
    src: '/assets/img/vehicle types/car types/CONVERTIBLE.webp',
  },
  {
    key: 9,
    name: 'Vintage Cars',
    options: 2,
    value: 'vintage_cars',
    src: '/assets/img/vehicle types/car types/VINTAGE CARS.webp',
  },
  {
    key: 10,
    name: 'Muscle Cars',
    options: 1,
    value: 'muscle_cars',
    src: '/assets/img/vehicle types/car types/MUSCLE CARS.webp',
  },
  {
    key: 11,
    name: 'Vans',
    options: 11,
    value: 'vans',
    src: '/assets/img/vehicle types/car types/VANs.webp',
  },
  {
    key: 12,
    name: 'Pickup Trucks',
    options: 12,
    value: 'pickup_trucks',
    src: '/assets/img/vehicle types/car types/PICKUP TRUCKS.webp',
  },
  {
    key: 13,
    name: 'Buses',
    options: 13,
    value: 'buses',
    src: '/assets/img/vehicle types/car types/BUSES.webp',
  },
  {
    key: 14,
    name: 'Buggy',
    options: 14,
    value: 'buggy',
    src: '/assets/img/vehicle types/car types/BUGGY.webp',
  },
  {
    key: 15,
    name: 'Special Edition',
    options: 15,
    value: 'special_edition',
    src: '/assets/img/vehicle types/car types/SPECIAL EDITION.webp',
  },
]
